sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: niconiconi
  huawei:
    endpoint:obs.cn-north-4.myhuaweicloud.com
    access-key-id:ZHFNNHUHP6JEWIGKE5EV
    access-key-secret:m8kOywWTSlGtm852HRqznVqwRouUQjyWPJLcpbcP
    bucket-name:skymeow